driver=com.ibm.db2.jcc.DB2Driver
url=jdbc:db2://10.86.180.76:50046/INGMTH
defaultSchemaName=INGMTHS
changeLogFile=liquibase-test-setup/changelogs/changelog_create_table.xml

# Liquibase parameter
appSchema=INGMTHS
