#<HEADER>
#<COPYRIGHT>
###############################################################
#  All right, title and interest in and to the software        
#  (the "Software") and the accompanying documentation or      
#  materials (the "Documentation"), including all proprietary  
#  rights, therein including all patent rights, trade secrets, 
#  trademarks and copyrights, shall remain the exclusive       
#  property of Electronic Data Systems LLC.            
#  No interest, licence or any right respecting the Software      
#  and the Documentation, other than expressly granted in      
#  the Software Licence Agreement, is granted by implication   
#  or otherwise.                                               
#                                                              
#  (C) Copyright 2000-2008 Electronic Data Systems LLC.
#  All rights reserved.                                        
#                                                              
#  Each Party agrees to (a) comply with all applicable laws    
#  regarding export or re-export of the Confidential           
#  Information, technical data, or derivatives of such items;  
#  and (b) not to export or re-export any such items to a      
#  destination or end user for which applicable law, including 
#  Canadian or U.S. law, requires an export license or other   
#  approval without first having obtained such license or      
#  approval.                                                   
###############################################################
#</COPYRIGHT>
#<HISTORY>
#<RELEASE>
#6.0
#</RELEASE>
#<NUMBER>
#014590
#</NUMBER>
#<COMMENT>
#New for release 6.0
#</COMMENT>
#</HISTORY>
#<HISTORY>
#<RELEASE>
#1.3
#</RELEASE>
#<COMMENT>
#changed EXIT to TERMINATE and button bar to OKButtonBar
#</COMMENT>
#</HISTORY>
#<HISTORY>
#<RELEASE>
#1.3
#</RELEASE>
#<NUMBER>
#19245
#</NUMBER>
#<COMMENT>
#Added new page to display date change message if produced
#</COMMENT>
#</HISTORY>
#</HEADER>
PROCESS ProcessProlog
{

	# Process code for authorization is 2
	LSIR-PRCES-CD = "2";
	# Get system authorization
	STEP GetAuthorization
	{
		USES P-STEP "BF0010-P";
	}

	# If the authorization failed, display a message, then
	# terminate the requested process.
	IF LSIR-RETURN-CD != "00"
	{
		Title = "Process Prolog";
		TitleBar = "TitleBar";
		TitleBarSize = "70";
		MessageFrame = "MessagesDisp";
		MessageFrameSize = "70";
		ButtonBar = "ButtonBarOK";
		ButtonBarSize = "40";
		STEP AuthFailed
		{
			USES S-STEP "AuthorizationFailed";
		}

		TERMINATE;

	}

	# If the system date change warning message is generated by BF0010
	# MIR-RETRN-CD 07 will be returned. It this case, display a page for the
	# message to appear on.
	IF MIR-RETRN-CD == "07"
	{
		Title = "Process Prolog";
		TitleBar = "TitleBar";
		TitleBarSize = "70";
		MessageFrame = "MessagesDisp";
		MessageFrameSize = "70";
		ButtonBar = "ButtonBarOK";
		ButtonBarSize = "40";
		STEP DateChange
		{
			USES S-STEP "ProcessPrologInformation";
		}

	}

	# Clear out any messages
	MESSAGES-T[0] = "";
}
