-- *********************************************************************
-- Update Database Script
-- *********************************************************************
-- Change Log: liquibase-test-setup/changelogs/changelog_alter_20260416.xml
-- Ran at: 4/16/26, 11:39 AM
-- Against: ingmths@jdbc:db2://10.86.180.76:50046/INGMTH
-- Liquibase version: 4.15.0
-- *********************************************************************

-- Lock Database
UPDATE "INGMTHS".DATABASECHANGELOGLOCK SET LOCKED = 1, LOCKEDBY = '673a838eb300 (172.17.0.3)', LOCKGRANTED = CURRENT TIMESTAMP WHERE ID = 1 AND LOCKED = 0;

-- Changeset liquibase-test-setup/Alter_DDL/ALTLQCVG_20260416.sql::alter_tlqcvg::firoz
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM"@

ALTER TABLE TLQCVG ADD COLUMN DESC_TXT VARCHAR(200) NOT NULL WITH DEFAULT ' '@

ALTER TABLE TLQCVG ADD COLUMN SRC_SYS CHAR(5) NOT NULL WITH DEFAULT ' '@

ALTER TABLE TLQCVG ADD COLUMN UPDATED_BY VARCHAR(30) NOT NULL WITH DEFAULT ' '@

ALTER TABLE TLQCVG ADD COLUMN DES_TXT VARCHAR(200) NOT NULL WITH DEFAULT ' '@

ALTER TABLE TLQCVG ADD COLUMN SRC_SYSTEM CHAR(5) NOT NULL WITH DEFAULT ' '@

ALTER TABLE TLQCVG ADD COLUMN UPDATED_ON VARCHAR(30) NOT NULL WITH DEFAULT ' '@

ALTER TABLE TLQCVG DROP COLUMN DESC_TXT@

ALTER TABLE TLQCVG DROP COLUMN SRC_SYS@

ALTER TABLE TLQCVG DROP COLUMN UPDATED_BY@

ALTER TABLE TLQCVG DROP COLUMN DES_TXT@

ALTER TABLE TLQCVG DROP COLUMN SRC_SYSTEM@

ALTER TABLE TLQCVG DROP COLUMN UPDATED_ON@

CALL SYSPROC.ADMIN_CMD('REORG TABLE TLQCVG')@

INSERT INTO "INGMTHS".DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, CONTEXTS, LABELS, LIQUIBASE, DEPLOYMENT_ID) VALUES ('alter_tlqcvg', 'firoz', 'liquibase-test-setup/Alter_DDL/ALTLQCVG_20260416.sql', CURRENT TIMESTAMP, 5, '8:427a5ec436ad5aa17d97d314ae78b040', 'sql', '', 'EXECUTED', NULL, NULL, '4.15.0', '6339592698');

-- Changeset liquibase-test-setup/changelogs/changelog_alter_20260416.xml::load_tlqbase_data::firoz
-- WARNING The following SQL may change each run and therefore is possibly incorrect and/or invalid:
INSERT INTO "INGMTHS".TLQBASE (ID, NAME, STATUS_CD, CREATED_BY, CREATED_TS) VALUES (6, 'DEL Record 6', 'A', 'LIQUIBASE', '2024-04-16 10:00:00');

INSERT INTO "INGMTHS".TLQBASE (ID, NAME, STATUS_CD, CREATED_BY, CREATED_TS) VALUES (7, 'DEL Record 7', 'A', 'LIQUIBASE', '2024-04-16 10:05:00');

INSERT INTO "INGMTHS".TLQBASE (ID, NAME, STATUS_CD, CREATED_BY, CREATED_TS) VALUES (8, 'DEL Record 8', 'I', 'LIQUIBASE', '2024-04-16 10:10:00');

INSERT INTO "INGMTHS".TLQBASE (ID, NAME, STATUS_CD, CREATED_BY, CREATED_TS) VALUES (9, 'DEL Record 6', 'A', 'LIQUIBASE', '2024-04-16 10:00:00');

INSERT INTO "INGMTHS".TLQBASE (ID, NAME, STATUS_CD, CREATED_BY, CREATED_TS) VALUES (10, 'DEL Record 7', 'A', 'LIQUIBASE', '2024-04-16 10:05:00');

INSERT INTO "INGMTHS".TLQBASE (ID, NAME, STATUS_CD, CREATED_BY, CREATED_TS) VALUES (11, 'DEL Record 8', 'I', 'LIQUIBASE', '2024-04-16 10:10:00');

INSERT INTO "INGMTHS".DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, CONTEXTS, LABELS, LIQUIBASE, DEPLOYMENT_ID) VALUES ('load_tlqbase_data', 'firoz', 'liquibase-test-setup/changelogs/changelog_alter_20260416.xml', CURRENT TIMESTAMP, 6, '8:ffa0c65ca70044725e459140b2ae49e7', 'loadData tableName=TLQBASE', '', 'EXECUTED', NULL, NULL, '4.15.0', '6339592698');

-- Release Database Lock
UPDATE "INGMTHS".DATABASECHANGELOGLOCK SET LOCKED = 0, LOCKEDBY = NULL, LOCKGRANTED = NULL WHERE ID = 1;

