-- liquibase formatted sql
-- changeset firoz:alter_tlqcvg endDelimiter:@

SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM"
@

--------------------------------
-- ADD COLUMNS (6 fields)
--------------------------------
ALTER TABLE TLQCVG ADD COLUMN DESC_TXT VARCHAR(200) NOT NULL WITH DEFAULT ' '
@
ALTER TABLE TLQCVG ADD COLUMN SRC_SYS CHAR(5) NOT NULL WITH DEFAULT ' '
@
ALTER TABLE TLQCVG ADD COLUMN UPDATED_BY VARCHAR(30) NOT NULL WITH DEFAULT ' '
@
ALTER TABLE TLQCVG ADD COLUMN DES_TXT VARCHAR(200) NOT NULL WITH DEFAULT ' '
@
ALTER TABLE TLQCVG ADD COLUMN SRC_SYSTEM CHAR(5) NOT NULL WITH DEFAULT ' '
@
ALTER TABLE TLQCVG ADD COLUMN UPDATED_ON VARCHAR(30) NOT NULL WITH DEFAULT ' '
@

-----------------------------------------
-- DROP COLUMNS (6 fields)
-----------------------------------------

ALTER TABLE TLQCVG DROP COLUMN DESC_TXT
@
ALTER TABLE TLQCVG DROP COLUMN SRC_SYS
@
ALTER TABLE TLQCVG DROP COLUMN UPDATED_BY
@
ALTER TABLE TLQCVG DROP COLUMN DES_TXT
@
ALTER TABLE TLQCVG DROP COLUMN SRC_SYSTEM
@
ALTER TABLE TLQCVG DROP COLUMN UPDATED_ON
@

----------------------------------
-- REORG
-----------------------------------
CALL SYSPROC.ADMIN_CMD('REORG TABLE TLQCVG')
@