-- liquibase formatted sql
-- changeset firoz:alter_tlqbase_v1 endDelimiter:@

SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM"
@

-- ========================
-- ALTER TYPE (3 alters)
-- ========================
ALTER TABLE TLQBASE ALTER COLUMN ID SET DATA TYPE BIGINT
@
ALTER TABLE TLQBASE ALTER COLUMN NAME SET DATA TYPE VARCHAR(100)
@
ALTER TABLE TLQBASE ALTER COLUMN CREATED_TS SET DATA TYPE TIMESTAMP
@

-- ========================
-- ADD COLUMNS (6 fields)
-- ========================
ALTER TABLE TLQBASE ADD COLUMN STATUS_CD CHAR(1) NOT NULL WITH DEFAULT 'A'
@
ALTER TABLE TLQBASE ADD COLUMN DESC_TXT VARCHAR(200)
@
ALTER TABLE TLQBASE ADD COLUMN SRC_SYS CHAR(5)
@
ALTER TABLE TLQBASE ADD COLUMN CREATED_BY VARCHAR(30)
@
ALTER TABLE TLQBASE ADD COLUMN UPDATED_BY VARCHAR(30)
@
ALTER TABLE TLQBASE ADD COLUMN UPDATED_TS TIMESTAMP
@

-- ========================
-- DROP COLUMNS (3 fields)
-- ========================
ALTER TABLE TLQBASE DROP COLUMN DESC_TXT
@
ALTER TABLE TLQBASE DROP COLUMN SRC_SYS
@
ALTER TABLE TLQBASE DROP COLUMN UPDATED_BY
@

-- ========================
-- REORG (MANDATORY for DB2)
-- ========================
CALL SYSPROC.ADMIN_CMD('REORG TABLE TLQBASE')
@

-- ========================
-- ROLLBACK
-- ========================
-- rollback CALL SYSPROC.ADMIN_CMD('REORG TABLE TLQBASE')
-- rollback ALTER TABLE TLQBASE ADD COLUMN DESC_TXT VARCHAR(200)
-- rollback ALTER TABLE TLQBASE ADD COLUMN SRC_SYS CHAR(5)
-- rollback ALTER TABLE TLQBASE ADD COLUMN UPDATED_BY VARCHAR(30)
-- rollback ALTER TABLE TLQBASE DROP COLUMN UPDATED_TS
-- rollback ALTER TABLE TLQBASE DROP COLUMN CREATED_BY
-- rollback ALTER TABLE TLQBASE DROP COLUMN STATUS_CD
-- rollback ALTER TABLE TLQBASE ALTER COLUMN CREATED_TS SET DATA TYPE TIMESTAMP
-- rollback ALTER TABLE TLQBASE ALTER COLUMN NAME SET DATA TYPE VARCHAR(50)
-- rollback ALTER TABLE TLQBASE ALTER COLUMN ID SET DATA TYPE INTEGER
@